baseURL = "/"
languageCode = "en-us"
title = "Just a bunch of stuff"
theme = "binario"

[pagination]
  pagerSize = 10

[Author]
  name = "asabla"
  bio = "Just your average developer monkey"
  related = true
  relatedMax = 5

[Params]
  authorbox = true

[Params.Entry]
  tor = true
  tocOpen = true

[Params.Featured]
  previewOnly = false

[Params.Breadcrumb]
  enable = true
  homeText = "Home"

[Params.Social]
  github = "asabla"


# Web App Manifest settings
# https://www.w3.org/TR/appmanifest/
# https://developers.google.com/web/fundamentals/web-app-manifest/
[Params.Manifest]
  name = "Just a bunch of stuff"
  shortName = "asabla blog"
  display = "browser"
  startUrl = "/"
  backgroundColor = "#2a2a2a"
  themeColor = "#1b1b1b"
  description = "Just your average developer monkey's blog"
  orientation = "portrait"
  scope = "/"

[outputFormats]
  [outputFormats.MANIFEST]
    mediaType = "application/json"
    baseName = "manifest"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "MANIFEST"]
